import { User, Post, Comment, CommentReplies, NotificationGroup } from "@/helpers/types";


// IMAGES

export const images: string[] = [
    "/images/user-3.jpg",
    "/images/user-2.jpg",
    "/images/user-3.jpg",
    "/images/user-2.jpg",
    "/images/user-3.jpg",
    "/images/user-2.jpg",
    "/images/user-3.jpg",
    "/images/user-3.jpg",
    "/images/user-2.jpg",
    "/images/user-3.jpg",
];


// USER

export const user: User = {
    id: 1,
    email: "ammar@example.com",
    username: "ammar_ch",
    name: "Ammar",
    profilePicture: "/images/user-1.jpg",
    bio: "Passionate developer and student.",
    links: [
        "https://github.com/ammarchaudhry5",
        "https://linkedin.com/in/ammar-chaudhry1",
    ],
    followers: [
        {
            id: 2,
            email: "john@example.com",
            username: "john_doe",
            name: "John Doe",
            profilePicture: "/images/user-2.jpg",
            bio: "Tech enthusiast.",
            links: [],
            followers: [],
            followersCount: 4,
            followings: [],
            followingsCount: 3,
            posts: [],
            postsCount: 1,
            savedPosts: [],
        },
        {
            id: 3,
            email: "ammar@example.com",
            username: "ammar_ch",
            name: "Ammar",
            profilePicture: "/images/user-1.jpg",
            bio: "Passionate developer and student.",
            links: [
                "https://github.com/ammarchaudhry5",
                "https://linkedin.com/in/ammar-chaudhry1",
            ],
            followers: [
                {
                    id: 4,
                    email: "john@example.com",
                    username: "john_doe",
                    name: "John Doe",
                    profilePicture: "/images/user-2.jpg",
                    bio: "Tech enthusiast.",
                    links: [],
                    followers: [],
                    followersCount: 4,
                    followings: [],
                    followingsCount: 3,
                    posts: [],
                    postsCount: 1,
                    savedPosts: [],
                },
            ],
            followersCount: 7,
            followings: [
                {
                    id: 5,
                    email: "sara@example.com",
                    username: "sara_123",
                    name: "Sara",
                    profilePicture: "/images/user-3.jpg",
                    bio: "Designer.",
                    links: [],
                    followers: [],
                    followersCount: 6,
                    followings: [],
                    followingsCount: 9,
                    posts: [],
                    postsCount: 2,
                    savedPosts: [],
                },
            ],
            followingsCount: 5,
            posts: [],
            postsCount: 1,
            savedPosts: [],
        },
        {
            id: 6,
            email: "ammar@example.com",
            username: "ammar_ch",
            name: "Ammar",
            profilePicture: "/images/user-1.jpg",
            bio: "Passionate developer and student.",
            links: [
                "https://github.com/ammarchaudhry5",
                "https://linkedin.com/in/ammar-chaudhry1",
            ],
            followers: [
                {
                    id: 7,
                    email: "john@example.com",
                    username: "john_doe",
                    name: "John Doe",
                    profilePicture: "/images/user-2.jpg",
                    bio: "Tech enthusiast.",
                    links: [],
                    followers: [],
                    followersCount: 4,
                    followings: [],
                    followingsCount: 3,
                    posts: [],
                    postsCount: 1,
                    savedPosts: [],
                },
            ],
            followersCount: 7,
            followings: [
                {
                    id: 8,
                    email: "sara@example.com",
                    username: "sara_123",
                    name: "Sara",
                    profilePicture: "/images/user-3.jpg",
                    bio: "Designer.",
                    links: [],
                    followers: [],
                    followersCount: 6,
                    followings: [],
                    followingsCount: 9,
                    posts: [],
                    postsCount: 2,
                    savedPosts: [],
                },
            ],
            followingsCount: 5,
            posts: [],
            postsCount: 1,
            savedPosts: [],
        },
    ],
    followersCount: 7,
    followings: [
        {
            id: 9,
            email: "sara@example.com",
            username: "sara_123",
            name: "Sara",
            profilePicture: "/images/user-3.jpg",
            bio: "Designer.",
            links: [],
            followers: [],
            followersCount: 6,
            followings: [],
            followingsCount: 9,
            posts: [],
            postsCount: 2,
            savedPosts: [],
        },
        {
            id: 10,
            email: "ammar@example.com",
            username: "ammar_ch",
            name: "Ammar",
            profilePicture: "/images/user-1.jpg",
            bio: "Passionate developer and student.",
            links: [
                "https://github.com/ammarchaudhry5",
                "https://linkedin.com/in/ammar-chaudhry1",
            ],
            followers: [
                {
                    id: 11,
                    email: "john@example.com",
                    username: "john_doe",
                    name: "John Doe",
                    profilePicture: "/images/user-2.jpg",
                    bio: "Tech enthusiast.",
                    links: [],
                    followers: [],
                    followersCount: 4,
                    followings: [],
                    followingsCount: 3,
                    posts: [],
                    postsCount: 1,
                    savedPosts: [],
                },
            ],
            followersCount: 7,
            followings: [
                {
                    id: 12,
                    email: "sara@example.com",
                    username: "sara_123",
                    name: "Sara",
                    profilePicture: "/images/user-3.jpg",
                    bio: "Designer.",
                    links: [],
                    followers: [],
                    followersCount: 6,
                    followings: [],
                    followingsCount: 9,
                    posts: [],
                    postsCount: 2,
                    savedPosts: [],
                },
            ],
            followingsCount: 5,
            posts: [],
            postsCount: 1,
            savedPosts: [],
        },
        {
            id: 13,
            email: "ammar@example.com",
            username: "ammar_ch",
            name: "Ammar",
            profilePicture: "/images/user-1.jpg",
            bio: "Passionate developer and student.",
            links: [
                "https://github.com/ammarchaudhry5",
                "https://linkedin.com/in/ammar-chaudhry1",
            ],
            followers: [
                {
                    id: 14,
                    email: "john@example.com",
                    username: "john_doe",
                    name: "John Doe",
                    profilePicture: "/images/user-2.jpg",
                    bio: "Tech enthusiast.",
                    links: [],
                    followers: [],
                    followersCount: 4,
                    followings: [],
                    followingsCount: 3,
                    posts: [],
                    postsCount: 1,
                    savedPosts: [],
                },
            ],
            followersCount: 7,
            followings: [
                {
                    id: 15,
                    email: "sara@example.com",
                    username: "sara_123",
                    name: "Sara",
                    profilePicture: "/images/user-3.jpg",
                    bio: "Designer.",
                    links: [],
                    followers: [],
                    followersCount: 6,
                    followings: [],
                    followingsCount: 9,
                    posts: [],
                    postsCount: 2,
                    savedPosts: [],
                },
            ],
            followingsCount: 5,
            posts: [],
            postsCount: 1,
            savedPosts: [],
        },
    ],
    followingsCount: 5,
    posts: [],
    postsCount: 1,
    savedPosts: [],
};

user.posts = [
    {
        id: 1,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-1.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 1!",
        comments: [],
    },
    {
        id: 2,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-2.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 2!",
        comments: [],
    },
    {
        id: 3,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-3.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 3!",
        comments: [],
    },
    {
        id: 4,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-2.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 2!",
        comments: [],
    },
    {
        id: 1,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-1.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 1!",
        comments: [],
    },
    {
        id: 4,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-2.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 2!",
        comments: [],
    },
    {
        id: 1,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-1.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 1!",
        comments: [],
    },
];


// COMMENT REPLIES

export const commentReplies: CommentReplies[] = [
    {
        id: 1,
        postId: 1,
        userId: 1,
        commentId: 1,
        userProfilePicture: user.profilePicture,
        username: user.name,
        comment: "first comment reply",
        time: "3h",
        likesCount: 8,
    },
    {
        id: 2,
        postId: 1,
        userId: 1,
        commentId: 1,
        userProfilePicture: user.profilePicture,
        username: user.name,
        comment: "second comment reply",
        time: "3h",
        likesCount: 8,
    },
    {
        id: 3,
        postId: 1,
        userId: 1,
        commentId: 1,
        userProfilePicture: user.profilePicture,
        username: user.name,
        comment: "third comment reply",
        time: "3h",
        likesCount: 8,
    },
];


// COMMENTS

export const comments: Comment[] = [
    {
        id: 1,
        postId: 1,
        userId: 1,
        userProfilePicture: user.profilePicture,
        username: user.name,
        comment: "first comment",
        commentReplies,
        time: "3h",
        likesCount: 8,
        repliesCount: 12,
    },
    {
        id: 2,
        postId: 1,
        userId: 1,
        userProfilePicture: user.profilePicture,
        username: user.name,
        comment: "second comment",
        commentReplies,
        time: "3h",
        likesCount: 8,
        repliesCount: 12,
    },
    {
        id: 3,
        postId: 1,
        userId: 1,
        userProfilePicture: user.profilePicture,
        username: user.name,
        comment: "third comment",
        commentReplies,
        time: "3h",
        likesCount: 8,
        repliesCount: 12,
    },
];


// POSTS

export const posts: Post[] = [
    {
        id: 1,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-1.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 1!",
        comments,
    },
    {
        id: 2,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-2.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 2!",
        comments,
    },
    {
        id: 3,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-3.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 3!",
        comments,
    },
];


// NOTIFICATIONS

export const notificationData: NotificationGroup[] = [
    {
        title: "This week",
        list: [
            {
                id: 1,
                users: [
                    {
                        id: 1,
                        username: "Arslan",
                        profilePicture: "/images/user-1.jpg",
                        email: "",
                        name: "",
                        bio: "",
                        links: [],
                        followers: [],
                        followersCount: 0,
                        followings: [],
                        followingsCount: 0,
                        posts: [],
                        postsCount: 0,
                        savedPosts: [],
                    },
                    {
                        id: 2,
                        username: "Sehrish",
                        profilePicture: "/images/user-2.jpg",
                        email: "",
                        name: "",
                        bio: "",
                        links: [],
                        followers: [],
                        followersCount: 0,
                        followings: [],
                        followingsCount: 0,
                        posts: [],
                        postsCount: 0,
                        savedPosts: [],
                    },
                ],
                action: "liked your post",
                time: "3d",
                previewImage: "/images/user-1.jpg",
            },
            {
                id: 2,
                users: [
                    {
                        id: 3,
                        username: "Rajkumar",
                        profilePicture: "/images/user-3.jpg",
                        email: "",
                        name: "",
                        bio: "",
                        links: [],
                        followers: [],
                        followersCount: 0,
                        followings: [],
                        followingsCount: 0,
                        posts: [],
                        postsCount: 0,
                        savedPosts: [],
                    },
                ],
                action: "liked your comment: Awesome",
                time: "3d",
                previewImage: "/images/user-1.jpg",
            },
            {
                id: 3,
                users: [
                    {
                        id: 1,
                        username: "Arslan",
                        profilePicture: "/images/user-1.jpg",
                        email: "",
                        name: "",
                        bio: "",
                        links: [],
                        followers: [],
                        followersCount: 0,
                        followings: [],
                        followingsCount: 0,
                        posts: [],
                        postsCount: 0,
                        savedPosts: [],
                    },
                    {
                        id: 2,
                        username: "Sehrish",
                        profilePicture: "/images/user-2.jpg",
                        email: "",
                        name: "",
                        bio: "",
                        links: [],
                        followers: [],
                        followersCount: 0,
                        followings: [],
                        followingsCount: 0,
                        posts: [],
                        postsCount: 0,
                        savedPosts: [],
                    },
                ],
                action: "liked your post",
                time: "3d",
                previewImage: "/images/user-1.jpg",
            },
            {
                id: 4,
                users: [
                    {
                        id: 3,
                        username: "Rajkumar",
                        profilePicture: "/images/user-3.jpg",
                        email: "",
                        name: "",
                        bio: "",
                        links: [],
                        followers: [],
                        followersCount: 0,
                        followings: [],
                        followingsCount: 0,
                        posts: [],
                        postsCount: 0,
                        savedPosts: [],
                    },
                ],
                action: "liked your comment: Awesome",
                time: "3d",
                previewImage: "/images/user-1.jpg",
            },
        ],
    },
    {
        title: "This month",
        list: [
            {
                id: 5,
                users: [
                    {
                        id: 5,
                        username: "Ali",
                        profilePicture: "/images/user-2.jpg",
                        email: "",
                        name: "",
                        bio: "",
                        links: [],
                        followers: [],
                        followersCount: 0,
                        followings: [],
                        followingsCount: 0,
                        posts: [],
                        postsCount: 0,
                        savedPosts: [],
                    },
                    {
                        id: 6,
                        username: "Subhan",
                        profilePicture: "/images/user-3.jpg",
                        email: "",
                        name: "",
                        bio: "",
                        links: [],
                        followers: [],
                        followersCount: 0,
                        followings: [],
                        followingsCount: 0,
                        posts: [],
                        postsCount: 0,
                        savedPosts: [],
                    },
                ],
                action: "liked your story",
                time: "6d",
                previewImage: "/images/user-1.jpg",
            },
            {
                id: 6,
                users: [
                    {
                        id: 10,
                        username: "Ahsan",
                        profilePicture: "/images/user-1.jpg",
                        email: "",
                        name: "",
                        bio: "",
                        links: [],
                        followers: [],
                        followersCount: 0,
                        followings: [],
                        followingsCount: 0,
                        posts: [],
                        postsCount: 0,
                        savedPosts: [],
                    },
                ],
                action: "started following you",
                time: "Nov 10",
                followBack: true,
            },
            {
                id: 7,
                users: [
                    {
                        id: 5,
                        username: "Ali",
                        profilePicture: "/images/user-2.jpg",
                        email: "",
                        name: "",
                        bio: "",
                        links: [],
                        followers: [],
                        followersCount: 0,
                        followings: [],
                        followingsCount: 0,
                        posts: [],
                        postsCount: 0,
                        savedPosts: [],
                    },
                    {
                        id: 6,
                        username: "Subhan",
                        profilePicture: "/images/user-3.jpg",
                        email: "",
                        name: "",
                        bio: "",
                        links: [],
                        followers: [],
                        followersCount: 0,
                        followings: [],
                        followingsCount: 0,
                        posts: [],
                        postsCount: 0,
                        savedPosts: [],
                    },
                ],
                action: "liked your story",
                time: "6d",
                previewImage: "/images/user-1.jpg",
            },
            {
                id: 8,
                users: [
                    {
                        id: 10,
                        username: "Ahsan",
                        profilePicture: "/images/user-1.jpg",
                        email: "",
                        name: "",
                        bio: "",
                        links: [],
                        followers: [],
                        followersCount: 0,
                        followings: [],
                        followingsCount: 0,
                        posts: [],
                        postsCount: 0,
                        savedPosts: [],
                    },
                ],
                action: "started following you",
                time: "Nov 10",
                followBack: true,
            },
        ],
    },
];
