import {User, Post, Comment, CommentReplies, NotificationGroup, Message, Conversation, Story,} from "@/helpers/types";
import {buildMessagesForConversation} from "@/helpers/sampleMessages"

// IMAGES

export const images: string[] = [
    "/images/user-3.jpg",
    "/images/user-2.jpg",
    "/images/user-3.jpg",
    "/images/user-2.jpg",
    "/images/user-3.jpg",
    "/images/user-2.jpg",
    "/images/user-3.jpg",
    "/images/user-3.jpg",
    "/images/user-2.jpg",
    "/images/user-3.jpg",
];


// USERS ARRAY - Sample users for reference

export const users: User[] = [
    {
        id: 1,
        email: "ammar@example.com",
        username: "ammar_ch",
        name: "Ammar",
        profilePicture: "/images/user-1.jpg",
        bio: "Passionate developer and student.",
        links: [
            "https://github.com/ammarchaudhry5",
            "https://linkedin.com/in/ammar-chaudhry1",
        ],
        followers: [],
        followersCount: 7,
        followings: [],
        followingsCount: 5,
        posts: [],
        postsCount: 1,
        savedPosts: [],
    },
    {
        id: 2,
        email: "john@example.com",
        username: "john_doe",
        name: "John Doe",
        profilePicture: "/images/user-2.jpg",
        bio: "Tech enthusiast.",
        links: [],
        followers: [],
        followersCount: 4,
        followings: [],
        followingsCount: 3,
        posts: [],
        postsCount: 1,
        savedPosts: [],
    },
    {
        id: 3,
        email: "sara@example.com",
        username: "sara_123",
        name: "Sara",
        profilePicture: "/images/user-3.jpg",
        bio: "Designer.",
        links: [],
        followers: [],
        followersCount: 6,
        followings: [],
        followingsCount: 9,
        posts: [],
        postsCount: 2,
        savedPosts: [],
    },
    {
        id: 4,
        email: "subhan@example.com",
        username: "i_subhan",
        name: "Subhan",
        profilePicture: "/images/user-1.jpg",
        bio: "Developer.",
        links: [],
        followers: [],
        followersCount: 10,
        followings: [],
        followingsCount: 8,
        posts: [],
        postsCount: 3,
        savedPosts: [],
    },
    {
        id: 5,
        email: "jawad@example.com",
        username: "jawad_khalid",
        name: "Jawad Khalid",
        profilePicture: "/images/user-2.jpg",
        bio: "Content creator.",
        links: [],
        followers: [],
        followersCount: 15,
        followings: [],
        followingsCount: 12,
        posts: [],
        postsCount: 5,
        savedPosts: [],
    },
    {
        id: 6,
        email: "ahmad@example.com",
        username: "ahmad_ahsan",
        name: "Ahmad Ahsan",
        profilePicture: "/images/user-1.jpg",
        bio: "Student.",
        links: [],
        followers: [],
        followersCount: 5,
        followings: [],
        followingsCount: 7,
        posts: [],
        postsCount: 2,
        savedPosts: [],
    },
];

// MAIN USER - Single user object (not array)

export const user: User = {
    id: 1,
    email: "ammar@example.com",
    username: "ammar_ch",
    name: "Ammar",
    profilePicture: "/images/user-1.jpg",
    bio: "Passionate developer and student.",
    links: [
        "https://github.com/ammarchaudhry5",
        "https://linkedin.com/in/ammar-chaudhry1",
    ],
    followers: [users[1], users[2]],
    followersCount: 7,
    followings: [users[2]],
    followingsCount: 5,
    posts: [],
    postsCount: 1,
    savedPosts: [],
};

user.posts = [
    {
        id: 1,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-1.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 1!",
        comments: [{
            id: 1,
            postId: 1,
            userId: 1,
            userProfilePicture: user.profilePicture,
            username: user.name,
            comment: "first comment",
            commentReplies: [],
            time: "3h",
            likesCount: 8,
            repliesCount: 12,
        }],
    },
    {
        id: 2,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-2.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 2!",
        comments: [],
    },
    {
        id: 3,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-3.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 3!",
        comments: [],
    },
    {
        id: 4,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-2.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 2!",
        comments: [],
    },
];


// COMMENT REPLIES

export const commentReplies: CommentReplies[] = [
    {
        id: 1,
        postId: 1,
        userId: 1,
        commentId: 1,
        userProfilePicture: user.profilePicture,
        username: user.name,
        comment: "first comment reply",
        time: "3h",
        likesCount: 8,
    },
    {
        id: 2,
        postId: 1,
        userId: 1,
        commentId: 1,
        userProfilePicture: user.profilePicture,
        username: user.name,
        comment: "second comment reply",
        time: "3h",
        likesCount: 8,
    },
    {
        id: 3,
        postId: 1,
        userId: 1,
        commentId: 1,
        userProfilePicture: user.profilePicture,
        username: user.name,
        comment: "third comment reply",
        time: "3h",
        likesCount: 8,
    },
];


// COMMENTS

export const comments: Comment[] = [
    {
        id: 1,
        postId: 1,
        userId: 1,
        userProfilePicture: user.profilePicture,
        username: user.name,
        comment: "first comment",
        commentReplies,
        time: "3h",
        likesCount: 8,
        repliesCount: 12,
    },
    {
        id: 2,
        postId: 1,
        userId: 1,
        userProfilePicture: user.profilePicture,
        username: user.name,
        comment: "second comment",
        commentReplies,
        time: "3h",
        likesCount: 8,
        repliesCount: 12,
    },
    {
        id: 3,
        postId: 1,
        userId: 1,
        userProfilePicture: user.profilePicture,
        username: user.name,
        comment: "third comment",
        commentReplies,
        time: "3h",
        likesCount: 8,
        repliesCount: 12,
    },
];


// POSTS

export const posts: Post[] = [
    {
        id: 1,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-1.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 1!",
        comments,
    },
    {
        id: 2,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-2.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 2!",
        comments,
    },
    {
        id: 3,
        userId: user.id,
        username: user.name,
        userProfilePicture: user.profilePicture,
        postedTime: "2h",
        posterImage: "/images/user-3.jpg",
        likesCount: 45,
        commentsCount: 10,
        description: "This is my new post 3!",
        comments,
    },
];


// NOTIFICATIONS

export const notificationData: NotificationGroup[] = [
    {
        title: "This week",
        list: [
            {
                id: 1,
                users: [users[1], users[2]],
                action: "liked your post",
                time: "3d",
                previewImage: "/images/user-1.jpg",
            },
            {
                id: 2,
                users: [users[2]],
                action: "liked your comment: Awesome",
                time: "3d",
                previewImage: "/images/user-1.jpg",
            },
            {
                id: 3,
                users: [users[1], users[2]],
                action: "liked your post",
                time: "3d",
                previewImage: "/images/user-1.jpg",
            },
            {
                id: 4,
                users: [users[2]],
                action: "liked your comment: Awesome",
                time: "3d",
                previewImage: "/images/user-1.jpg",
            },
        ],
    },
    {
        title: "This month",
        list: [
            {
                id: 5,
                users: [users[1], users[2]],
                action: "liked your story",
                time: "6d",
                previewImage: "/images/user-1.jpg",
            },
            {
                id: 6,
                users: [users[3]],
                action: "started following you",
                time: "Nov 10",
                followBack: true,
            },
            {
                id: 7,
                users: [users[1], users[2]],
                action: "liked your story",
                time: "6d",
                previewImage: "/images/user-1.jpg",
            },
            {
                id: 8,
                users: [users[3]],
                action: "started following you",
                time: "Nov 10",
                followBack: true,
            },
        ],
    },
];

// STORIES

export const stories: Story[] = [
    { id: 1, userId: 1, username: 'Your note', profilePicture: '/images/user-1.jpg', hasNew: false, isNote: true, noteText: 'Note...' },
    { id: 2, userId: 2, username: 'faizan', profilePicture: '/images/user-2.jpg', hasNew: true },
    { id: 3, userId: 3, username: 'راج', profilePicture: '/images/user-3.jpg', hasNew: true },
];

// MESSAGES

export const messages: Message[] = [
    {
        id: 1,
        senderId: users[5],
        receiverId: user,
        content: 'Mentioned you in their story',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'story-reply',
        storyReply: {
            storyOwner: '@Ammar Chaudhry',
            storyImage: '/images/user-1.jpg',
        },
    },
    {
        id: 2,
        senderId: user,
        receiverId: users[1],
        content: 'Ok',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'reaction',
    },
    {
        id: 3,
        senderId: users[5],
        receiverId: user,
        content: 'Wah wah wah',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'text',
    },
    {
        id: 4,
        senderId: user,
        receiverId: users[5],
        content: 'Ok',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'reaction',
    },
    {
        id: 5,
        senderId: users[5],
        receiverId: user,
        content: 'Wah wah wah',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'text',
    },
    {
        id: 6,
        senderId: user,
        receiverId: users[5],
        content: 'Ok',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'reaction',
    },
    {
        id: 7,
        senderId: users[5],
        receiverId: user,
        content: 'Wah wah wah',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'text',
    },
    {
        id: 8,
        senderId: user,
        receiverId: users[5],
        content: 'Ok',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'reaction',
    },
    {
        id: 9,
        senderId: users[5],
        receiverId: user,
        content: 'Wah wah wah',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'text',
    },
    {
        id: 10,
        senderId: user,
        receiverId: users[5],
        content: 'Ok',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'reaction',
    },
    {
        id: 11,
        senderId: users[5],
        receiverId: user,
        content: 'Wah wah wah',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'text',
    },
    {
        id: 12,
        senderId: user,
        receiverId: users[5],
        content: 'Ok',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'reaction',
    },
    {
        id: 13,
        senderId: users[5],
        receiverId: user,
        content: 'Wah wah wah',
        timestamp: 'Wed 7:14 PM',
        isRead: true,
        type: 'text',
    },
];

// CONVERSATIONS

export const conversations: Conversation[] = [
    {
        id: 1,
        userId: users[5],
        lastMessage: "3 lakh dollars 😂😊",
        timestamp: "1d",
        isOnline: false,
        unreadCount: 0,
        isMuted: false,
        senderUsername: users[5],
        senderName: users[5],
        senderUserProfilePicture: users[5],
        receiverUsername: users[1],
        receiverName: users[1],
        receiverUserProfilePicture: users[1],
        messages: buildMessagesForConversation(users[5], user, 50),
        hasAttachment: false,
        reactionEmoji: undefined
    },
    {
        id: 2,
        userId: users[0],
        lastMessage: "😂😊",
        timestamp: "1d",
        isOnline: true,
        unreadCount: 1,
        isMuted: false,
        senderUsername: users[0],
        senderName: users[0],
        senderUserProfilePicture: users[0],
        receiverUsername: users[1],
        receiverName: users[1],
        receiverUserProfilePicture: users[1],
        messages: buildMessagesForConversation(users[0], user, 50)
    },
    {
        id: 3,
        userId: users[1],
        lastMessage: "Anas sent an attachment.",
        timestamp: "1d",
        isOnline: true,
        unreadCount: 1,
        isMuted: true,
        hasAttachment: true,
        senderUsername: users[1],
        senderName: users[1],
        senderUserProfilePicture: users[1],
        receiverUsername: users[1],
        receiverName: users[1],
        receiverUserProfilePicture: users[1],
        messages: buildMessagesForConversation(users[1], user, 50)
    },
    {
        id: 4,
        userId: users[2],
        lastMessage: "Wah wah wah",
        timestamp: "1d",
        isOnline: false,
        unreadCount: 0,
        isMuted: true,
        senderUsername: users[2],
        senderName: users[2],
        senderUserProfilePicture: users[2],
        receiverUsername: users[1],
        receiverName: users[1],
        receiverUserProfilePicture: users[1],
        messages: buildMessagesForConversation(users[2], user, 50)
    },
    {
        id: 5,
        userId: users[3],
        lastMessage: "Reacted 😊 to your message",
        timestamp: "1d",
        isOnline: false,
        unreadCount: 0,
        isMuted: false,
        reactionEmoji: '😊',
        senderUsername: users[3],
        senderName: users[3],
        senderUserProfilePicture: users[3],
        receiverUsername: users[1],
        receiverName: users[1],
        receiverUserProfilePicture: users[1],
        messages: buildMessagesForConversation(users[3], user, 50)
    },
    {
        id: 6,
        userId: users[4],
        lastMessage: "Reacted 😊 to your message",
        timestamp: "1d",
        isOnline: true,
        unreadCount: 1,
        isMuted: true,
        reactionEmoji: '😊',
        senderUsername: users[4],
        senderName: users[4],
        senderUserProfilePicture: users[4],
        receiverUsername: users[1],
        receiverName: users[1],
        receiverUserProfilePicture: users[1],
        messages: buildMessagesForConversation(users[4], user, 50)
    }
];
